Fix/og tags improvements
Afordin/hackafor pull request #20
Opened 2023-09-29 01:26 UTC by JoeMancera

# 🧵 Descripción

He agregado los tags perdidos de la PR #13 con algunas mejoras en el copy para resolver el issue #16 

## 🎨 Tipo del cambio

Por favor selecciona las opciones que apliquen en tu PR.

- [x] Frontend
- [ ] Backend
- [ ] Configuración
- [x] Documentación

---

- [ ] Bug fix (cambio no radical que soluciona un problema)
- [ ] New feature (cambio no radical que añade funcionalidad)
- [ ] Breaking change (solución o característica que haría que la funcionalidad existente no funcionara como se esperaba)

## 🧩 Otra información

He usado [esta página](https://en.rakko.tools/tools/9/) web para poder replicar el cómo se vería en las distintas redes y adjunto algunos pantallazos de ello. Creo que @JavierBalonga me lo mencionó en aquel PR

Facebook
![image](https://github.com/Afordin/hackafor/assets/43323828/9da00192-f42c-4f40-819f-34da5b2b2040)

Twiter X
![image](https://github.com/Afordin/hackafor/assets/43323828/95be9bb3-c22e-4df9-bd83-a9e348b5abf8)

2023-09-29 07:54 UTC, owlnai commented on README.md
> +Puedes ver el archivo [contributing](https://github.com/Afordin/hackafor/blob/main/.github/CONTRIBUTING.md) para ver más información.
¿No se puede usar una URL relativa?

2023-09-29 07:55 UTC, owlnai commented on apps/front/index.html
> +  <meta property="og:image" content="/og-image-hackafor.webp" />
No todos soportan WebP en OpenGraph:
![image](https://github.com/Afordin/hackafor/assets/20427094/ec0b716e-fbb6-4c02-80a1-f492f95ae23f)

2023-09-29 07:57 UTC, owlnai requested changes
Gracias por la PR! Por favor, revisa lo del WebP ❤️

2023-09-29 12:07 UTC, JoeMancera commented on README.md
> +Puedes ver el archivo [contributing](https://github.com/Afordin/hackafor/blob/main/.github/CONTRIBUTING.md) para ver más información.
La he cambiado. Desde el VSCode pareciera que no la tomaba por el '.' Pero lo he logrado tomar de allí.

2023-09-29 12:08 UTC, JoeMancera commented on apps/front/index.html
> +  <meta property="og:image" content="/og-image-hackafor.webp" />
He agregado la imagen con formato JPEG. He dejado la webP por si se necesita a posteriori.

2023-09-29 12:16 UTC, owlnai commented on README.md
> +Puedes ver el archivo [contributing](https://github.com/Afordin/hackafor/blob/main/.github/CONTRIBUTING.md) para ver más información.
Probablemente porque VSCode toma en cuenta las rutas del sistema de archivos (local), no el de GitHub

2023-09-29 12:17 UTC, owlnai commented on apps/front/index.html
> +  <meta property="og:image" content="/og-image-hackafor.webp" />
Si usamos Vercel (desconozco si sigue siendo la idea), enviará el WebP automáticamente a aquellos que lo soporten

2023-10-02 21:11 UTC, JoeMancera commented
Hola @owlnai, 

Tengo una preguntita, ¿hay algún otro punto de mejora en la PR?

2023-10-02 21:14 UTC, owlnai commented
Ah, sorry. No podía aprobarlo desde la app y se me pasó luego. Está todo en orden! 😅

2023-10-02 21:14 UTC, owlnai commented on README.md
> +- [JSDoc](https://jsdoc.app/) - Documentation generator
Está bien pero procura dejar esto para otra PR ^^

2023-10-02 21:14 UTC, owlnai approved these changes

2023-10-02 21:15 UTC, merged